version: "3.9"

services:
  rust:
    container_name: rust
    image: nalex/rust:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://alexis:12345@db:5432/rust_api_database
    depends_on:
      - db
  
  db:
    container_name: db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alexis
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=rust_api_database
    volumes:
      - rust_api_data:/var/lib/postgresql/data

volumes:
  rust_api_data: {}